### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by luckykelfor** [Dragonexio/OpenApi#5]
Using the python api, I found that after some requests, I always got the connection error:
http.client.RemoteDisconnected: Remote end closed connection without response

the full stack is like:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): openapi.dragonex.io:443
Traceback (most recent call last):
  File "D:\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "D:\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 308, in connect
    self._tunnel()
  File "D:\Python\Python37-32\lib\http\client.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "D:\Python\Python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

T**raceback (most recent call last):
  File "D:\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openapi.dragonex.io', port=443): Max retries exceeded with url: /api/v1/market/real/?symbol_id=125 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

_Traceback (most recent call last):
  File ".\test.py", line 58, in <module>
    new_check_price = float(dragonex.get_market_real(symbol_map["abt_usdt"]).data[0]['close_price'])
  File "D:\FastWorkspace\Secrete\OpenApi\examples\python3\dragonex.py", line 90, in get_market_real
    return self.get(path, params)
  File "D:\FastWorkspace\Secrete\OpenApi\examples\python3\base.py", line 44, in get
    rsp = requests.get(url=url, params=params, headers=headers)
  File "D:\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\Python37-32\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='openapi.dragonex.io', port=443): Max retries exceeded with url: /api/v1/market/real/?symbol_id=125 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))**_

Do you have any idea?

**Comment by Dragonexio** [comment]
you can use openapi.dragonex.co
